import matplotlib.dates as mdates
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import tomllib
from labellines import labelLines
from matplotlib.lines import Line2D

plt.style.use("dark_background")

# Use pandas to read the csv data files
df_type1 = pd.read_csv("TYPEI_DATA.csv", header=0)
df_type2 = pd.read_csv("TYPEII_DATA.csv", header=0)
df_metadata = pd.read_csv("METADATA.csv", header=0)

# Useful parameters for the plot
min_tof = df_metadata["Min TOF [Days]"][0]
max_tof = df_metadata["Max TOF [Days]"][0]
max_c3 = df_metadata["Max C3 [km^2/s^2]"][0]

# x_type1,y_type1 => dtype = datetime64[ns] (numpy)
x_type1 = pd.to_datetime(df_type1["Departure Date [JD]"], origin="julian", unit="D")
y_type1 = pd.to_datetime(df_type1["Arrival Date [JD]"], origin="julian", unit="D")
x_type2 = pd.to_datetime(df_type2["Departure Date [JD]"], origin="julian", unit="D")
y_type2 = pd.to_datetime(df_type2["Arrival Date [JD]"], origin="julian", unit="D")

# Convert BEFORE passing to tricontour
x_type1_num = mdates.date2num(x_type1.dt.to_pydatetime())
y_type1_num = mdates.date2num(y_type1.dt.to_pydatetime())
x_type2_num = mdates.date2num(x_type2.dt.to_pydatetime())
y_type2_num = mdates.date2num(y_type2.dt.to_pydatetime())

# Calculate time of flight for type I and type II trajectories
tof_type1 = y_type1_num - x_type1_num
tof_type2 = y_type2_num - x_type2_num


# Type I and II Departure and Arrival Energies (C3) [km^2/s^2]
C3_dep_type1 = df_type1["Departure C3 [km^2/s^2]"]
C3_arr_type1 = df_type1["Arrival C3 [km^2/s^2]"]
C3_dep_type2 = df_type2["Departure C3 [km^2/s^2]"]
C3_arr_type2 = df_type2["Arrival C3 [km^2/s^2]"]


# Type I and II Departure and Arrival Delta-V [km/s]
deltaV_dep_type1 = np.sqrt(C3_dep_type1)
deltaV_arr_type1 = np.sqrt(C3_arr_type1)
deltaV_dep_type2 = np.sqrt(C3_dep_type2)
deltaV_arr_type2 = np.sqrt(C3_arr_type2)

# Type I and II Departure Launch Asymptotes
dla_type1 = df_type1["Departure Launch Asymptote [deg]"]
dla_type2 = df_type2["Departure Launch Asymptote [deg]"]

# Type I and II Arrival Launch Asymptotes
rla_type1 = df_type1["Arrival Launch Asymptote [deg]"]
rla_type2 = df_type2["Arrival Launch Asymptote [deg]"]

# Store all tofs in an array
tofs = np.array([tof_type1, tof_type1, tof_type2, tof_type2])

# Store all delta-vs in an array
delta_vs = np.array(
    [deltaV_dep_type1, deltaV_arr_type1, deltaV_dep_type2, deltaV_arr_type2]
)


# Function that takes a set of clabels and draws a bbox behind it for clearer visibility
def add_bbox(label_set):
    for label in label_set:
        label.set_bbox(dict(facecolor="black", edgecolor="none", pad=0.1))
        label.set_rotation(0)


# TOF vs Delta-V plot
def plot_tof_vs_DV(pmin: float, pmax: float):
    # Temporary array that will be filld in clipped values from all delta_vs
    temp = []

    # Clipping
    for i in range(len(delta_vs)):
        min = np.percentile(delta_vs[i], pmin)
        max = np.percentile(delta_vs[i], pmax)
        cap = np.clip(delta_vs[i], a_min=min, a_max=max)
        temp.append(cap)

    # Store in numpy arr
    capped_delta_vs = np.array(temp)

    # Create fig + ax objects
    fig, axs = plt.subplots(2, 2)

    # Flatten axes for easier plotting
    flat_axs = axs.flatten()

    # Scatter plot
    for i in range(len(capped_delta_vs)):
        ax = flat_axs[i]

        ax.scatter(tofs[i], capped_delta_vs[i], s=0.1, color=f"C{i}")
        ax.grid(True, linestyle="dotted", alpha=0.3)

    # Formatting
    fig.suptitle("TOF vs. Delta-V", weight="bold")
    fig.supylabel("Delta-V [km/s]", weight="bold")
    fig.supxlabel("Time of Flight (TOF) [Days]", weight="bold")
    # Custom legend format
    custom_lines = [
        Line2D([0], [0], color="C1", lw=1),
        Line2D([0], [0], color="C2", lw=1),
        Line2D([0], [0], color="C3", lw=1),
        Line2D([0], [0], color="C4", lw=1),
    ]
    fig.legend(
        custom_lines,
        ["Departure Type I", "Arrival Type I", "Departure Type II", "Arrival Type II"],
        ncol=4,
        loc="lower center",
        fontsize=5,
        bbox_to_anchor=(0.5, 0.05),
    )
    fig.tight_layout()
    fig.savefig("/Users/mihir/projects/porkchop/docs/tof_vs_deltaV.png", dpi=300)


# Main Porkchop Plot
def plot_contour(
    dep_levels: np.ndarray,  # show launch levels
    arr_levels: np.ndarray,  # show arrival levels
    rla_levels,
    dla_levels,
    plot_departure=True,  # show launch C3 plot
    plot_arrival=False,  # show arrival C3 plot
    tof_contour=False,  # show tof plot
    dla=False,  # show declination of launch asymptote
    rla=False,  # show right ascension of launch asymptote
    x_cuts=(0, 0),  # x-axis limits, but it subtracts from default axis
    y_cuts=(0, 0),  # same as x_cuts, but for y-axis
):

    # This will subtract or cut away from the time window generated by the Rust solver
    # to get desired framing or to just zoom in
    xmin_cut, xmax_cut = x_cuts
    ymin_cut, ymax_cut = y_cuts

    # Some constants for the plot
    c_fontsize = 10
    lws = 0.5

    # Create fig + ax objects
    fig, ax = plt.subplots(figsize=(7, 7))

    dep_lbl_1 = None
    dep_lbl_2 = None
    arr_lbl_1 = None
    arr_lbl_2 = None

    # Departure C3 Energies (I & II)
    if plot_departure:
        # Type 1 Departure Energy Contour Lines
        type1_dep_lines = ax.tricontour(
            x_type1_num,  # <-- original floats from Julian Date
            y_type1_num,
            C3_dep_type1,
            levels=dep_levels,
            cmap="Blues",
            linewidths=lws,
        )
        dep_lbl_1 = ax.clabel(
            type1_dep_lines,
            inline=False,
            fontsize=c_fontsize,
            fmt="%.0f",
            colors="white",
        )

        # Type 2 Departure Energy Contour Lines
        type2_dep_lines = ax.tricontour(
            x_type2_num,
            y_type2_num,
            C3_dep_type2,
            levels=dep_levels,
            cmap="Blues",
            linewidths=lws,
        )
        dep_lbl_2 = ax.clabel(
            type2_dep_lines,
            inline=False,
            inline_spacing=0,
            fontsize=c_fontsize,
            fmt="%.0f",
            colors="white",
        )

        add_bbox(dep_lbl_1)
        add_bbox(dep_lbl_2)

    # Arrical C3 Energies (I & II)
    if plot_arrival:
        # Type 1 Arrival Energy Contour Lines
        type1_arr_lines = ax.tricontour(
            x_type1_num,
            y_type1_num,
            C3_arr_type1,
            levels=arr_levels,
            cmap="Reds_r",
            linewidths=lws,
            alpha=0.99,
        )
        arr_lbl_1 = ax.clabel(
            type1_arr_lines,
            inline=False,
            fontsize=c_fontsize,
            fmt="%.0f",
            colors="#d9311e",
        )

        # Type 2 Arrival Energy Contour Lines
        type2_arr_lines = ax.tricontour(
            x_type1_num,
            y_type1_num,
            C3_arr_type2,
            levels=arr_levels,
            cmap="Reds_r",
            linewidths=lws,
            alpha=0.99,
        )
        arr_lbl_2 = ax.clabel(
            type2_arr_lines,
            inline=False,
            fontsize=c_fontsize,
            fmt="%.0f",
            colors="#d9311e",
        )

        add_bbox(arr_lbl_1)
        add_bbox(arr_lbl_2)

    # Delcination of Launch Asymptote
    if dla:
        if dep_lbl_1 is not None:
            for label in dep_lbl_1:
                label.remove()
        if dep_lbl_2 is not None:
            for label in dep_lbl_2:
                label.remove()
        if arr_lbl_1 is not None:
            for label in arr_lbl_1:
                label.remove()
        if arr_lbl_2 is not None:
            for label in arr_lbl_2:
                label.remove()

        levels = dla_levels
        dla_t1_lines = ax.tricontour(
            x_type1_num,
            y_type1_num,
            dla_type1,
            levels=levels,
            colors="red",
            linewidths=0.6,
        )
        dla_label_1 = ax.clabel(
            dla_t1_lines,
            inline=True,
            fontsize=10,
            fmt="%.0f",
            colors="red",
        )

        dla_t2_lines = ax.tricontour(
            x_type2_num,
            y_type2_num,
            dla_type2,
            levels=levels,
            colors="red",
            linewidths=0.6,
        )
        dla_label_2 = ax.clabel(
            dla_t2_lines,
            inline=True,
            fontsize=10,
            fmt="%.0f",
            colors="red",
        )

        add_bbox(dla_label_1)
        add_bbox(dla_label_2)

    # Right Ascension of Launch
    if rla:
        if dep_lbl_1 is not None:
            for label in dep_lbl_1:
                label.remove()
        if dep_lbl_2 is not None:
            for label in dep_lbl_2:
                label.remove()
        if arr_lbl_1 is not None:
            for label in arr_lbl_1:
                label.remove()
        if arr_lbl_2 is not None:
            for label in arr_lbl_2:
                label.remove()

        levels = rla_levels
        rla_t1_lines = ax.tricontour(
            x_type1_num,
            y_type1_num,
            rla_type1,
            levels=levels,
            colors="#fc6f0a",
            linewidths=0.3,
        )
        rla_lbl_1 = ax.clabel(
            rla_t1_lines,
            inline=True,
            fontsize=10,
            fmt="%.0f",
            colors="#fc6f0a",
        )
        rla_t2_lines = ax.tricontour(
            x_type2_num,
            y_type2_num,
            rla_type2,
            levels=levels,
            colors="#fc6f0a",
            linewidths=0.3,
        )
        rla_lbl_2 = ax.clabel(
            rla_t2_lines,
            inline=True,
            fontsize=10,
            fmt="%.0f",
            colors="#fc6f0a",
        )

        add_bbox(rla_lbl_1)
        add_bbox(rla_lbl_2)

    # TOF Contours Lines
    if tof_contour:
        # tof_lbl = None
        min = np.min(x_type1_num) + xmin_cut
        max = np.max(x_type1_num) - xmax_cut
        # annotations = []
        for tof in np.linspace(min_tof, max_tof, 7):
            xs = np.linspace(min, max, 2)
            y_lines = xs + tof  # y = x + TOF (constant TOF line)
            ax.plot(
                xs, y_lines, "white", lw=1, alpha=0.9, label=f"{tof:.0f}", linestyle=":"
            )

        labelLines(ax.get_lines(), align=True, clip_on=True, xvals=min + 20, fontsize=6)

    """
    To mark a single point on the plot:
    ax.scatter(
        mdates.date2num(np.datetime64("2020-07-30")),
        mdates.date2num(np.datetime64("2021-02-18")),
        label="Perserverance",
        c='r',
        marker='x'
    )
    """

    # Axis Date Formatting
    ax.xaxis.set_major_locator(mdates.MonthLocator(interval=2))
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%m/%d/%Y"))

    ax.yaxis.set_major_locator(mdates.MonthLocator(interval=3))
    ax.yaxis.set_major_formatter(mdates.DateFormatter("%m/%d/%Y"))

    # Axis Label Formatting
    ax.tick_params(axis="x", labelsize=8)
    ax.tick_params(axis="y", labelsize=8)

    # Axis Limits Formatting
    ax.set_xlim(np.min(x_type1_num) + xmin_cut, np.max(x_type1_num) - xmax_cut)
    ax.set_ylim(np.min(x_type1_num) + ymin_cut, np.max(y_type1_num) - ymax_cut)

    # Plot Formatting
    plt.title("2026 Earth-Mars Ballistic Transfer Trajectories", weight="bold")
    plt.xlabel("Launch Date", weight="bold")
    plt.ylabel("Arrival Date", weight="bold")

    # fig.autofmt_xdate(rotation=15, ha="right") # uncomment to rotate launch date labels
    plt.grid(True, linestyle="dotted", alpha=0.3)

    # Legend line formatting
    lines = [
        Line2D([0], [0], color="#d9311e", lw=1),  # arrival
        Line2D([0], [0], color="#5aa5e8", lw=1),  # departure
        Line2D([0], [0], color="red", lw=1),  # dla
    ]

    # For consisent legend labeling:
    match (plot_departure, plot_arrival, dla):
        case (True, True, False):  # arrival + departure
            plt.legend(
                lines,
                ["Arrival C3 [${km^2}/{s^2}$]", "Departure C3 [${km^2}/{s^2}$]"],
            )
        case (True, False, False):  # departure only
            plt.legend(
                lines[1:],
                ["Departure C3 [${km^2}/{s^2}$]"],
            )
        case (False, True, False):  # arrival only
            plt.legend(
                lines[:1],
                ["Arrival C3 [${km^2}/{s^2}$]"],
            )
        case (False, False, True):  # dla
            plt.legend(
                lines[:2],
                ["Declination of Launch Asymptote [deg]"],
            )
        case (True, True, True):  # arrival + departure + dla
            plt.legend(
                lines,
                [
                    "Arrival C3 [${km^2}/{s^2}$]",
                    "Departure C3 [${km^2}/{s^2}$]",
                    "Declination of Launch Asymptote [deg]",
                ],
            )
        case (True, False, True):  # departure only + dla
            plt.legend(
                lines[1:],
                [
                    "Departure C3 [${km^2}/{s^2}$]",
                    "Declination of Launch Asymptote [deg]",
                ],
            )
        case (False, True, True):  # arrival only + dla
            plt.legend(
                lines[::2],
                [
                    "Arrival C3 [${km^2}/{s^2}$]",
                    "Declination of Launch Asymptote [deg]",
                ],
            )
        case (False, False, False):  #  none
            pass

    plt.tight_layout()

    # Save the plot as a png
    plt.savefig("/Users/mihir/projects/porkchop/docs/porkchop_plot.png", dpi=300)
    # plt.show()


departure_levels = np.linspace(0, max_c3, 18)
arrival_levels = np.linspace(0, max_c3, 12)


if __name__ == "__main__":
    # Load the config.toml file
    with open("/Users/mihir/projects/porkchop/config.toml", "rb") as f:
        config = tomllib.load(f)
    py_inputs = config["python_config"]

    # Assign variables to each config
    plot_departure = py_inputs["plot_departure_contours"]
    plot_arrival = py_inputs["plot_arrival_contours"]
    plot_tof_contours = py_inputs["plot_tof_contours"]
    plot_dla = py_inputs["plot_dla"]
    dla_levels = py_inputs["dla_levels"]
    rla_levels = py_inputs["rla_levels"]
    plot_rla = py_inputs["plot_rla"]
    x_cuts = tuple(py_inputs["x_cuts"])
    y_cuts = tuple(py_inputs["y_cuts"])

    plot_contour(
        departure_levels,
        arrival_levels,
        dla_levels=dla_levels,
        rla_levels=rla_levels,
        tof_contour=plot_tof_contours,
        plot_departure=plot_departure,
        plot_arrival=plot_arrival,
        dla=plot_dla,
        rla=plot_rla,
        x_cuts=x_cuts,
        y_cuts=y_cuts,
    )

    # plot_tof_vs_DV(pmin=10, pmax=40)
